name: Build Trickster image
on:
  workflow_dispatch:

jobs:
  push:
    name: Build Trickster image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get short SHA
        run: echo "sha7=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: "Dockerfile"
          push: true
          tags: >
            ghcr.io/${{ github.repository }}:${{ env.sha7 }}
          platforms: |
            linux/arm64
            linux/amd64
      - name: Output image tags
        run: |
          echo "## Built images with the following tags" >> $GITHUB_STEP_SUMMARY
          echo "### ghcr.io/${{ github.repository }}:${{ env.sha7 }}" >> $GITHUB_STEP_SUMMARY
